name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.3'

      - name: Set up protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.31.0

      - name: Set up protoc-gen-go-grpc
        run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0

      - name: Build
        run:  make go
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.GO_DEPLOY_KEY }}
        with:
          source-directory: go
          destination-github-username: 'isd-sgcu'
          destination-repository-name: 'rpkm67-go-proto'
          user-email: isd.team.sgcu@gmail.com
          target-branch: ${{ steps.extract_branch.outputs.branch }}
          create-target-branch-if-needed: true